//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public string lastname { get; set; }
        public string name { get; set; }
        public string ptronymic { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string passportSeries { get; set; }
        public string passportNumber { get; set; }
        public System.DateTime birth { get; set; }
        public Nullable<System.DateTime> lastAuth { get; set; }
        public Nullable<int> authType_id { get; set; }
        public int gender_id { get; set; }
    
        public virtual AuthTypes AuthTypes { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
